compressionLevel: mixed

enablGlobalCache: true

gitHooksPath: .github/hooks

nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnrc/plugin-git-hooks.cjs
    spec: 'https://raw.githubusercontent.com/trufflehq/yarn-plugin-git-hooks/main/bundles/%40yarnpkg/plugins-git-hooks.js'

yatnPath: .yarn/releases/yarn-4-4-1.cjs